### ISSUE TITLE
TypeError getPaletteSync is not a function

### ISSUE THREAD

**Issue by 0rsa** [Assembless/react-native-material-you#1]
Hi,
I have this error when I try to use getPaletteSync at runtime
`TypeError: (0, _$$_REQUIRE(_dependencyMap[9], "@assembless/react-native-material-you").getPaletteSync) is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[9], "@assembless/react-native-material-you").getPaletteSync)()', '(0, _$$_REQUIRE(_dependencyMap[9], "@assembless/react-native-material-you").getPaletteSync)' is undefined)`

I use react-native 0.66.1

**Comment by DRFR0ST** [comment]
Hi, I'm sorry for the bug and the delay. The package has been accidentally pushed to the "beta" channel instead of "latest". The package will be improved in the coming 2 weeks with more React compatibility and will translation over to a stable release. We plan to support the package long term and make it as useful as possible.

To test the `1.0.0-beta.2` current release, please upgrade the package: `yarn upgrade @assembless/react-native-material-you@latest`.
It should work properly now.

Once again I'm really sorry for the mistake. It's completely on our side. Have fun using the package and I would love to hear feedback from you. 😃
