### ISSUE TITLE
Following guide does not work

### ISSUE THREAD

**Issue by 0rsa** [Assembless/react-native-material-you#4]
1.0.0-beta.3.

```
const App = () => (
    <MaterialYouService>
        {...}
    </MaterialYouService>
)

const MyComponent = () => {
    const { palette } = useMaterialYouPalette();
```
does not work, palette is undefined

```
import { useMaterialYou } from '@assembless/react-native-material-you';

const MyComponent = () => {
    const { palette } = useMaterialYou();
```

generates an error
TypeError: null is not an object (evaluating 'React.useContext(MaterialYouContext).palette')

A mix of both
```
const App = () => (
    <MaterialYouService>
        {...}
    </MaterialYouService>
)

const MyComponent = () => {
    const { palette } = useMaterialYou();
```

is working. Palette is an object of system_accentx

Is the guide obsolete?

**Comment by DRFR0ST** [comment]
I'm still working on the documentation and API. It's still in beta. But I'm very grateful for the issues, it's very very helpful, thank you.

The example seems to work with `const palette = useMaterialYouPalette()`, I've corrected the documentation a few minutes ago.

Mix of both is unnecessary since `MaterialYouService` is using `useMaterialYou` to get the palette and also subscribes to the native method that asynchronously retrieves the regenerated palette from the Native side instead of forcing the developer to call `_refresh` each time the wallpaper changes.

Use `useMaterialYou` hook if you don't care about refreshing the palette when wallpaper changes/system decides to regenerate the colors.

**Comment by DRFR0ST** [comment]
I've published a more specific documentation generated from JSDoc here: https://assembless.github.io/react-native-material-you/index.html

Let me know if you find anything suspicious. ^^

**Comment by DRFR0ST** [comment]
also btw. can I include you in special thanks section for contributors and testers? You have been very helpful! Thank you! 🥇

**Comment by 0rsa** [comment]
I confirm this is working removing brackets
From
`const { palette } = useMaterialYouPalette();`
To
`const palette = useMaterialYouPalette();`
Thanks

> also btw. can I include you in special thanks section for contributors and testers?
no problem!
