### ISSUE TITLE
Feat: Fallback for non supported device

### ISSUE THREAD

**Issue by ShivamJoker** [Assembless/react-native-material-you#5]
It would be better if we can have an option to add fallback colors for non supported devices like < Android 12 and iOS

**Comment by 0rsa** [comment]
+1, with default colors which can be set up.

Thanks

**Comment by DRFR0ST** [comment]
Thanks for your feature request. We've just released another beta (`1.0.0-beta.4`) which adds the option to provide a `fallbackPalette`. We've tested it on few Android versions that don't support Material You down to level 23 (Android 6). Have fun testing and I would love to hear some feedback since we're still in beta and need feedback a lot.

**Comment by ShivamJoker** [comment]
That's awesome I'll test it out 😄
